### ISSUE TITLE
Проверить ДЗ "Расчет топлива" и "Расчет кол-ва рулонов обоев"

### ISSUE THREAD

**Issue by evgeniychernyshev** [evgeniychernyshev/python-course#1]

**Comment by coursar** [comment]
Зачем закрылии issue? не нужно уже проверять?

**Comment by evgeniychernyshev** [comment]
Создал отдельные репозитории для каждой задачи, чтобы не лежало все в одной куче. В collaborators также добавил.

**Comment by coursar** [comment]
Тогда этот можно удалить
